pull_request_rules:
  - name: Auto-merge Dependabot pull requests
    conditions:
      - and:
          - author~=^dependabot(|-preview)\[bot\]$
          - check-success=Vercel
    actions:
      merge:
        method: merge