pull_request_rules:
  - name: Auto-merge security vulnerabilities when build passes and there are no conflicts
    conditions:
      - and:
          - author=dependabot
          - check-success=Vercel
    actions:
      merge:
        method: merge